import L from "leaflet";
import { API_BASE_URL } from "./constants";

/**
 * Returns the color for a given geometry type.
 * @param {*} d
 * @returns
 */
export function getColor(d) {
  return d === "City" || d === "C"
    ? "#3A27D0"
    : d === "District" || d === "D"
      ? "#f04b23"
      : d === "Administrative district" || d === "A"
        ? "#ffcc00"
        : d === "Federal state" || d === "F"
          ? "#469F4E"
          : "#ff7f00";
}

/**
 * Loads the geometries for the given search IDs and adds them to the map.
 * @param {*} searchIDs
 * @param {*} mapRef
 */
export async function loadGeometries(searchIDs, map) {
  const { cityLayer, districtLayer, adLayer, fsLayer } = map.layers;
  const data = await fetchGeometries(searchIDs);

  data.forEach((item) => {
    const color = getColor(item.type);

    const layer = L.geoJSON(item.geometry, {
      style: {
        color,
        fillColor: color,
        weight: 3,
        opacity: 0.65,
        fillOpacity: 0.35,
      },
      onEachFeature: (_, l) => l.bindPopup(item.name),
      pane: item.type,
    });

    switch (item.type) {
      case "C":
        cityLayer.addLayer(layer);
        break;
      case "D":
        districtLayer.addLayer(layer);
        break;
      case "A":
        adLayer.addLayer(layer);
        break;
      case "F":
        fsLayer.addLayer(layer);
        break;
      default:
        break;
    }
  });

  const group = L.featureGroup([cityLayer, districtLayer, adLayer, fsLayer]);
  map.flyToBounds(group.getBounds());
}

/**
 * Removes all geometries from the map
 */
export function clearGeometries(mapRef) {
  if (!mapRef.current?.layers) return;

  const { cityLayer, districtLayer, adLayer, fsLayer } = mapRef.current.layers;
  cityLayer.clearLayers();
  districtLayer.clearLayers();
  adLayer.clearLayers();
  fsLayer.clearLayers();
}

/**
 * Recursively search for keys in an object that match a certain pattern.
 * Generated by ChatGPT.
 */
export function findKeysRecursively(obj, ids) {
  let patternID = /[A-Z]*ID[A-Z]*/;
  let patternName = /[A-Z]*Name[A-Z]*/;
  // Search until obj is null or not an object
  if (obj === null || typeof obj !== "object") {
    return;
  }

  let id = null;
  let name = null;

  // Search for the ID
  Object.keys(obj).forEach((key) => {
    if (patternID.test(key)) {
      id = obj[key];
    }
    if (patternName.test(key)) {
      name = obj[key];
    }

    // Call function recursively
    if (typeof obj[key] === "object") {
      findKeysRecursively(obj[key], ids);
    }
  });

  if (id !== null) {
    ids.push({ id: id, name: name });
  }
}

/**
 * Fetches geometry data for the given search IDs.
 * @param {Array} searchIDs - An array of objects containing ID and name properties.
 */
export async function fetchGeometries(searchIDs) {
  let ids = [];
  searchIDs.forEach((item) => {
    if (item.name !== null) {
      ids.push(item.id);
    }
  });
  const res = await fetch(
    `${API_BASE_URL}/api/geometries?ids=` + ids.join(","),
  );
  const rows = await res.json();

  return searchIDs
    .map((item) => {
      const result = rows.geometries.find((row) => row.id === item.id);

      if (!result) return null;
      if (item.name == null) return null;

      return {
        id: item.id,
        name: item.name,
        type: item.id[0],
        geometry: result.geojson,
      };
    })
    .filter(Boolean);
}

/**
 * Exports a Leaflet layer or all map layers as a GeoJSON file.
 * @param {L.Layer | string} layerOrKey - Either a Leaflet layer object or a key from map.layers (e.g., 'cityLayer')
 * @param {L.Map} map - The Leaflet map instance
 * @param {string} filename - Optional filename
 */
export function exportLayerToGeoJSON(
  layerOrKey,
  map,
  filename = "map-export.geojson",
) {
  let layer;

  // Fall 1: Es wurde ein Key übergeben (z.B. 'cityLayer'), wir holen den Layer aus der Map-Instanz
  if (typeof layerOrKey === "string") {
    layer = map.layers[layerOrKey];
  } else {
    // Fall 2: Es wurde direkt ein Layer-Objekt übergeben
    layer = layerOrKey;
  }

  if (!layer || layer.getLayers().length === 0) {
    alert("Keine Daten in diesem Layer zum Exportieren vorhanden.");
    return;
  }

  try {
    // 1. Konvertierung in GeoJSON
    const geojsonData = layer.toGeoJSON();

    // 2. In JSON-String umwandeln (mit Einrückung für Lesbarkeit)
    const jsonString = JSON.stringify(geojsonData, null, 2);

    // 3. Blob erstellen
    const blob = new Blob([jsonString], { type: "application/json" });
    const url = URL.createObjectURL(blob);

    // 4. Download-Link temporär erstellen und auslösen
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();

    // 5. Aufräumen
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error("Export failed:", error);
    alert("Ein Fehler ist beim Export aufgetreten.");
  }
}
