import L from "leaflet";

/**
 * Returns the color for a given geometry type.
 * @param {*} d
 * @returns
 */
export function getColor(d) {
  return d === "City" || d === "C"
    ? "#3A27D0"
    : d === "District" || d === "D"
      ? "#f04b23"
      : d === "Administrative district" || d === "A"
        ? "#ffcc00"
        : d === "Federal state" || d === "F"
          ? "#469F4E"
          : "#ff7f00";
}

/**
 * Loads the geometries for the given search IDs and adds them to the map.
 * @param {*} searchIDs
 * @param {*} mapRef
 */
export async function loadGeometries(searchIDs, map) {
  const { cityLayer, districtLayer, adLayer, fsLayer } = map.layers;
  const data = await fetchGeometries(searchIDs);

  data.forEach((item) => {
    const color = getColor(item.type);

    const layer = L.geoJSON(item.geometry, {
      style: {
        color,
        fillColor: color,
        weight: 3,
        opacity: 0.65,
        fillOpacity: 0.35,
      },
      onEachFeature: (_, l) => l.bindPopup(item.name),
      pane: item.type,
    });

    switch (item.type) {
      case "C":
        cityLayer.addLayer(layer);
        break;
      case "D":
        districtLayer.addLayer(layer);
        break;
      case "A":
        adLayer.addLayer(layer);
        break;
      case "F":
        fsLayer.addLayer(layer);
        break;
      default:
        break;
    }
  });

  const group = L.featureGroup([cityLayer, districtLayer, adLayer, fsLayer]);
  map.flyToBounds(group.getBounds());
}

/**
 * Removes all geometries from the map
 */
export function clearGeometries(mapRef) {
  if (!mapRef.current?.layers) return;

  const { cityLayer, districtLayer, adLayer, fsLayer } = mapRef.current.layers;
  cityLayer.clearLayers();
  districtLayer.clearLayers();
  adLayer.clearLayers();
  fsLayer.clearLayers();
}

/**
 * Recursively search for keys in an object that match a certain pattern.
 * Generated by ChatGPT.
 */
export function findKeysRecursively(obj, ids) {
  let patternID = /[A-Z]*ID[A-Z]*/;
  let patternName = /[A-Z]*Name[A-Z]*/;
  // Search until obj is null or not an object
  if (obj === null || typeof obj !== "object") {
    return;
  }

  let id = null;
  let name = null;

  // Search for the ID
  Object.keys(obj).forEach((key) => {
    if (patternID.test(key)) {
      id = obj[key];
    }
    if (patternName.test(key)) {
      name = obj[key];
    }

    // Call function recursively
    if (typeof obj[key] === "object") {
      findKeysRecursively(obj[key], ids);
    }
  });

  if (id !== null) {
    ids.push({ id: id, name: name });
  }
}

/**
 * Fetches geometry data for the given search IDs.
 * @param {Array} searchIDs - An array of objects containing ID and name properties.
 */
export async function fetchGeometries(searchIDs) {
  let ids = [];
  searchIDs.forEach((item) => {
    if (item.name !== null) {
      ids.push(item.id);
    }
  });
  const res = await fetch(
    "http://localhost:8000/api/geometries?ids=" + ids.join(","),
  );
  const rows = await res.json();

  return searchIDs
    .map((item) => {
      const result = rows.geometries.find((row) => row.id === item.id);

      if (!result) return null;
      if (item.name == null) return null;

      return {
        id: item.id,
        name: item.name,
        type: item.id[0],
        geometry: result.geojson,
      };
    })
    .filter(Boolean);
}
