import { useEffect, useRef } from "react";
import L from "leaflet";

export default function Map({ mapInstanceRef }) {
  const mapRef = useRef(null);

  useEffect(() => {
    if (!mapRef.current) return;

    // Map initialisieren
    const map = L.map(mapRef.current).setView(
      [51.51588878700843, 7.475327389339492],
      7,
    );

    // To make the map globally
    mapInstanceRef.current = map;

    const fsLayer = L.featureGroup().addTo(map);
    const adLayer = L.featureGroup().addTo(map);
    const districtLayer = L.featureGroup().addTo(map);
    const cityLayer = L.featureGroup().addTo(map);

    mapInstanceRef.current.layers = {
      cityLayer,
      districtLayer,
      adLayer,
      fsLayer,
    };

    // Base Layer
    const osm = L.tileLayer(
      "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
      {
        attribution:
          '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
        maxZoom: 18,
      },
    ).addTo(map);

    // Layer Control
    const baseMaps = { OpenStreetMap: osm };
    const overlayMaps = {
      Cities: cityLayer,
      Districts: districtLayer,
      "Administrative Districts": adLayer,
      "Federal States": fsLayer,
    };

    L.control.layers(baseMaps, overlayMaps).addTo(map);

    // Fixed z-index for layers
    map.createPane("F");
    map.getPane("F").style.zIndex = 400;

    map.createPane("A");
    map.getPane("A").style.zIndex = 410;

    map.createPane("D");
    map.getPane("D").style.zIndex = 420;

    map.createPane("C");
    map.getPane("C").style.zIndex = 430;

    // Legend
    const legend = L.control({ position: "bottomleft" });

    legend.onAdd = function () {
      const div = L.DomUtil.create("div", "info legend");

      const categories = [
        "City",
        "District",
        "Administrative district",
        "Federal state",
      ];

      div.innerHTML =
        "<strong>Federal Levels</strong><br>" +
        categories
          .map(
            (c) =>
              '<i class="bi bi-circle-fill" style="color:' +
              getColor(c) +
              '" ></i> ' +
              (c ? c : "+"),
          )
          .join("<br>");

      div.style.backgroundColor = "rgba(255,255,255,0.7)";
      return div;
    };

    legend.addTo(map);

    // Cleanup beim Unmount (WICHTIG!)
    return () => {
      map.remove();
    };
  }, [mapInstanceRef]);

  return <div ref={mapRef} style={{ height: "470px", width: "100%" }} />;
}

function getColor(d) {
  return d === "City" || d === "C"
    ? "#3A27D0"
    : d === "District" || d === "D"
      ? "#f04b23"
      : d === "Administrative district" || d === "A"
        ? "#ffcc00"
        : d === "Federal state" || d === "F"
          ? "#469F4E"
          : "#ff7f00";
}

export async function loadGeometries(searchIDs, mapRef) {
  const map = mapRef.current;
  const { cityLayer, districtLayer, adLayer, fsLayer } = map.layers;
  const data = await fetchGeometries(searchIDs);

  data.forEach((item) => {
    const color = getColor(item.type);

    const layer = L.geoJSON(item.geometry, {
      style: {
        color,
        fillColor: color,
        weight: 3,
        opacity: 0.65,
        fillOpacity: 0.35,
      },
      onEachFeature: (_, l) => l.bindPopup(item.name),
      pane: item.type,
    });

    switch (item.type) {
      case "C":
        cityLayer.addLayer(layer);
        break;
      case "D":
        districtLayer.addLayer(layer);
        break;
      case "A":
        adLayer.addLayer(layer);
        break;
      case "F":
        fsLayer.addLayer(layer);
        break;
      default:
        break;
    }
  });

  const group = L.featureGroup([cityLayer, districtLayer, adLayer, fsLayer]);
  map.flyToBounds(group.getBounds());
}

/**
 * Removes all geometries from the map
 */
export function clearGeometries(mapRef) {
  if (!mapRef.current?.layers) return;

  const { cityLayer, districtLayer, adLayer, fsLayer } = mapRef.current.layers;
  cityLayer.clearLayers();
  districtLayer.clearLayers();
  adLayer.clearLayers();
  fsLayer.clearLayers();
}

/**
 * Recursively search for keys in an object that match a certain pattern.
 * Generated by ChatGPT.
 */
export function findKeysRecursively(obj, ids) {
  let patternID = /[A-Z]*ID[A-Z]*/;
  let patternName = /[A-Z]*Name[A-Z]*/;
  // Search until obj is null or not an object
  if (obj === null || typeof obj !== "object") {
    return;
  }

  let id = null;
  let name = null;

  // Search for the ID
  Object.keys(obj).forEach((key) => {
    if (patternID.test(key)) {
      id = obj[key];
    }
    if (patternName.test(key)) {
      name = obj[key];
    }

    // Call function recursively
    if (typeof obj[key] === "object") {
      findKeysRecursively(obj[key], ids);
    }
  });

  if (id !== null) {
    ids.push({ id: id, name: name });
  }
}

export async function fetchGeometries(searchIDs) {
  let ids = [];
  searchIDs.forEach((item) => {
    if (item.name !== null) {
      ids.push(item.id);
    }
  });
  const res = await fetch(
    "http://localhost:8000/api/geometries?ids=" + ids.join(","),
  );
  const rows = await res.json();

  return searchIDs
    .map((item) => {
      const result = rows.geometries.find((row) => row.id === item.id);

      if (!result) return null;
      if (item.name == null) return null;

      return {
        id: item.id,
        name: item.name,
        type: item.id[0],
        geometry: result.geojson,
      };
    })
    .filter(Boolean);
}
